DELETE FROM CUSTOMER;
DELETE FROM HOURLY_WAGE;
DELETE FROM WORKING_RECORD;
DELETE FROM SALARY;
DELETE FROM LOGIN_INFORMATION;
DELETE FROM GAIN_AND_LOSS;
DELETE FROM ORDER_LIST;
DELETE FROM ORDERS;
DELETE FROM SALE_LIST;
DELETE FROM SALE;
DELETE FROM RETURN_LIST;
DELETE FROM INVENTORY;
DELETE FROM EMPLOYEE;
DELETE FROM POSITION;
DELETE FROM BRANCH;

